global d
d = {
'asciidoc-version': '{asciidoc-version}\r\n',
'admonitionparagraph': '[NOTE]\r\npara\r\n\r\n',
'backgroundblock': '&&&&\r\ncontent\r\n&&&&\r\n\r\n',
'bulleted_list': '- item\r\n\r\n- item\r\n\r\n',
'callout_list': '<1> item \r\n<2> item\r\n\r\n',
'callout_inlinemacro': '<1> item \r\n<2> item\r\n\r\n',
'footnote': 'content1 footnote:[text] content2 footnote:[text]\r\n\r\n',
'footnoteref1': 'content1 footnoteref:[id1] content2 footnoteref:[id2]\r\n\r\n',
'footnoteref2': 'content1 footnoteref:[id1,text1] content2 footnoteref:[id2,text2]\r\n\r\n',
'imagesblock': 'images::backends/slidy2/tests/i1.png[backends/slidy2/tests/i1.png,backends/slidy2/tests/i1.png]\r\n',
'labeled_list': 'label1::\r\nitem\r\nlabel2::\r\nitem\r\n\r\n',
'listingblock': '----\r\nlisting\r\n----\r\n\r\n',
'literalblock': '.......\r\nliteral\r\n.......\r\n\r\n',
'numbered_list': '. item\r\n\r\n. item\r\n\r\n',
'nopagebreak': '{slidepagebreak}XXX\r\n\r\n>>>\r\n{slidepagebreak}YYY\r\n\r\n== section\r\n{slidepagebreak}ZZZ\r\n',
'openblock': '\r\n1. item\r\n+\r\n--\r\nText ...\r\n--\r\n\r\n',
'pagebreak': '\r\n<<<\r\ncontent\r\n{slidepagebreak}XXX\r\n',
'paragraph': 'para \r\n\r\n',
'qanda_list': '[qanda]\r\nquestion 1::\r\nanswer\r\nquestion 2::\r\nanswer\r\n\r\n',
'quoteblock': '[quote, Name, Title]\r\n____\r\ncitation\r\n____\r\n\r\n',
'sect1': '== title level 1\r\ncontent\r\n\r\n',
'sect2': '=== title level 2\r\ncontent\r\n\r\n',
'sect3': '==== title level 3\r\ncontent\r\n\r\n',
'sect4': '===== title level 4\r\ncontent\r\n\r\n',
'appendix': '[appendix]\r\n== title\r\ncontent\r\n\r\n',
'table': '[width="15%"]\r\n|====\r\n|1|2\r\n|A|B\r\n|====\r\n\r\n',
'verseblock': '[verse, Name, Title]\r\n____\r\ncitation\r\n____\r\n\r\n'
}